<?php

/**
 * @file
 * This is a module that covers a variety of small changes.
 */

/**
 * Implements hook_theme_suggestions_field_alter().
 */
function localgov_search_theme_suggestions_field_alter(array &$suggestions, array $variables) {
  if (
    $variables['element']['#field_name'] === 'body' &&
    $variables['element']['#view_mode'] === 'localgov_site_search_result'
    ) {
    $suggestions[] = 'field__body__' . $variables['element']['#view_mode'];
  }
}

/**
 * Implements hook_theme_suggestions_form_element_label().
 */
function localgov_search_theme($existing, $type, $theme, $path) {
  return [
    'field__body__localgov_site_search_result' => [
      'base hook' => 'field',
      'template' => 'field--body--localgov-site-search-result',
    ],
  ];
}

function localgov_search_page_attachments(array &$variables) {
  $variables['#attached']['library'][] = 'localgov_search/global-styling';
}